### ISSUE TITLE
give users the option to visualize and interactively subset a csv file from the virtual watershed

### ISSUE THREAD

**Issue by mt-digital** [mtpain/vwplatform#33] opened 2015-06-15 19:03 UTC
To start, include this option at the files view page as a button. The files view is currently only accessible from the Share module: http://vw.nkn.uidaho.edu/share/

The user clicks "View and add files for this resource" on an existing resource and they see this page:

![screen shot 2015-06-15 at 11 21 59 am](https://cloud.githubusercontent.com/assets/2425472/8167082/c934236c-1350-11e5-907c-70132be9e577.png)

There are currently buttons for OGS services, download, and removal. Add a "visualize/subset" button if the file extension is csv so users can use the visualization/subsetting tools.

Create a new Blueprint called visualize with a url: vw.nkn.uidaho.edu/visualize. Here give the user the option to subset the data as well. See the structure of `app/__init__.py` and `manage.py` to learn how blueprints are used in this project and read the Flask docs on modular applications with blueprints: http://flask.pocoo.org/docs/0.10/blueprints/

Users will have access to this via the search page as well when #32 is fixed.

**Comment by ruiwu1990** [comment] 2015-06-24 20:29
First version (will be finished before July 3): 
1) users need to manually enter visualization section through the link: http://127.0.0.1:5000/visualization/
2) users can visualize csv files only 
3) visualize methods: line charts, bar charts, pie charts
4) users can download line charts chosen part as a csv file
5) the visualization section will just have an index.html

**Comment by ruiwu1990** [comment] 2015-06-24 20:40
Here is a question: I should put my js files in vwplatform/app/templates/visualization/js , right?

**Comment by mt-digital** [comment] 2015-06-24 21:26
That depends, do you actually use templating in your javascript files? If so, then yes put them there. 

If not, you should put them in vwplatform/app/static/js. Apparently I have been putting javascript files just under `app/static`, but if you add more, we should probably organize them better. So please create `app/static/js` and put your new javascript files there if they aren't templates.

**Comment by ruiwu1990** [comment] 2015-06-24 21:30
I need to create my js files to visualize data, such as lineChart.js. Therefore, I will put them in vwplatform/app/templates/visualization/js

**Comment by ruiwu1990** [comment] 2015-06-24 21:31
Also, where should I store users' upload files? And where can I get access to the existing data files to visualize?

**Comment by mt-digital** [comment] 2015-06-25 23:51
Look at how Lisa has implemented uploads in the share Blueprint. She creates a directory called "uploads" if it doesn't exist yet. She can also answer your questions regarding issue #37, which she has already done.

**Comment by ruiwu1990** [comment] 2015-06-25 23:55
Thank you. I will ask her. She will be back next week.

**Comment by ruiwu1990** [comment] 2015-07-01 19:54
I have a suggestion: I found Lisa has done something that enable users to upload files and download files. How about adding a visualization button in the Service and Download column? When users click visualization button, the system requires users to input the row offset and column offset of the csv file (I need to get rid of the metadata of the csv file to visualize it). Then the system will go to /visualization/rowoffset/columnoffset and display the visualization results. If you agree with this idea, I need Lisa's help. Lisa should add the "visualization" button and bring the download url of the csv file from frontend (html) to backend (flask).
![screenshot from 2015-07-01 12 46 38](https://cloud.githubusercontent.com/assets/8552440/8463468/5282c5f6-1fef-11e5-89ce-4416c6f247ff.png)

**Comment by mt-digital** [comment] 2015-07-01 21:34
I like this. There is one issue: single points are often not of interest. What would be more interesting is to calculate the sum or average of particular variables over the entire grid for a particular timestep, or to make a map of a single variable. With NetCDF, you'll be able to access variables individually and then do these operations.

I really like the idea of using the URL to access the column/row offset, but I don't see it working too well in the bigger picture. So would you please focus on making an interface for visualization of a single NetCDF? So when a user clicks the button as you're proposing, they are taken to an interface that allows them to interact and plot things from the NetCDF.

Do some research, there are some tools out there that can do parts of this, but none do it all well, and none are connected to our virtual watershed platform. This is where you come in!

**Comment by ruiwu1990** [comment] 2015-07-01 21:44
OK. I will create a sub-section in visualization for NetCDF visualization. This includes an interface for users to choose which part to visualize. Can you email me a NetCDF file first to test?

**Comment by mt-digital** [comment] 2015-07-01 21:46
try this: http://vwp-dev.unm.edu/apps/vwp/datasets/4a79a65f-05f5-4bc1-8a75-59dbe0b0edaf/flat_input.nc.original.nc

There are many input bands here. There's some complications because there are fill values that are very large if there is missing data. I'm not sure yet how to handle that the right way, but for now I do like I do in this post I sent you: https://mt.northwestknowledge.net/netcdf/python/2015/06/29/xray-day-one.html

Under "Example" I do this:

``` python
mpp_series[mpp_series > 1e6] = 0.0
```

to set everything larger than 1M to be zero before I do any aggregation.

**Comment by ruiwu1990** [comment] 2015-07-01 21:50
Second version (will be finished before July 10):
1) users need to manually enter NetCDF visualization section through the link: http://127.0.0.1:5000/visualization/NetCDF
2) users can visualize NetCDF files with line chart
3) the system offers users different options to visualize (which variable)

I will focus on  second version first and then I will work on link all the visualization parts with files stored in the virtual watershed server.

**Comment by ruiwu1990** [comment] 2015-07-07 20:44
Got one question about accessing values of one variable, named 'm_pp', from this file (http://vwp-dev.unm.edu/apps/vwp/datasets/4a79a65f-05f5-4bc1-8a75-59dbe0b0edaf/flat_input.nc.original.nc).

I used these commands (netcdf4 library) to access variable values:
netcdf_aim_file = Dataset(filename, "r")
netcdf_aim_file.variables['m_pp'][1][3][3]  # dimensions is (time, northing, easting)

The return value is "masked". This means this value is too big right? I used the same command to access another value:
netcdf_aim_file.variables['I_lw'][1][2][3]

The return value is normal: 303.92157. Therefore I believe my method is right, the problem is some of the values are NaN or too big. This situation brings another question: if I use this method to access value, and the value is "masked", is that fine that I replace this value with a specific value like 0?

**Comment by mt-digital** [comment] 2015-07-08 16:09
That's right, those large values are missing values. Keeping them as "missing" helps save some space, I guess. NetCDF puts the floating point maximum in as a placeholder. In the case of m_pp, "mass flux of precipitation", it doesn't rain or snow every hour, so for hours when there was no precipitation all precipitation variables (including m_pp) will be masked. Try inspecting `netcdf_aim_file.variables['m_pp'][6]`. The values at this time step should not be masked.

For now, any time you encounter these masked values you can just set them to zero. I think eventually I will set those to zero so we won't have to deal with masked values at all.

**Comment by ruiwu1990** [comment] 2015-07-10 21:28
Sorry that I cannot finish the first version of NetCDF file Visualization today. I will work on it this weekend and finish them for sure. Sorry again.

**Comment by ruiwu1990** [comment] 2015-07-12 19:46
Life is hard and programming is harder. I got a hard question about accessing NetCDF file data. Could you guys give me some suggestions? My pipeline to visualize NetCDF file is: 1) choose a NetCDF file; 2) choose one variable and one dimension from that variable to visualize in line chart (e.g. a user choose a variable named temperature and temperature has three dimensions: time(size 16), lon(size 148), lat(size 170). The user decides to visualize temperature and time in a line chart); 3) specify the left dimension (e.g.  since the user has chosen to visualize time and temperature, the system needs to enable user to specify lat and lon. If the user chooses lon to be 30 and lat to be 15. Then the system needs to obtain NetCDF data by using netcdf_aim_file.variables['temperature'][0][30][15], netcdf_aim_file.variables['temperature'][1][30][15] ... netcdf_aim_file.variables['temperature'][15][30][15]); 4) The system visualizes the obtained data

Here is the hard problem: I am not sure which variable and the attribute the user will choose, then it means i cannot set up a simple for loop to obtain data by using netcdf_aim_file.variables['temperature'][x][30][15]

I tried to use one dimension to replace multi-dimensions by using netcdf_aim_file.variables['temperature'][1_148_170+1*170+1] to replace netcdf_aim_file.variables['temperature'][1][1][1]. However, it seems netcdf4 library does not support that. Please give me some suggestions how to handle this problem. Thanks so much.

**Comment by ruiwu1990** [comment] 2015-07-12 21:26
Problem fixed! You know why I still have some good feelings, after I was beat badly by my program, I still have the chance to kick its ass back.

**Comment by ruiwu1990** [comment] 2015-07-12 22:32
Just finish the first version of NetCDF visualization with line chart. The clone url is:
https://github.com/ruiwu1990/vwplatform.git

For this version, users need to go to http://127.0.0.1:5000/visualization/NetCDF/
manually. The system now using a sample file for this version (users cannot choose which file to visualize). This version cannot handle variables whose attributes value is "masked" (e.g. m_pp). I suggest you choose I_lw to test (most of others just have unique values.) I compare the outputs results with ncview (another good software). They look similar. After you view the results and want to visualize another variable, please manually go to http://127.0.0.1:5000/visualization/NetCDF/

I am not sure if I merged with Matthew's last change or not. I will figure it out tomorrow.

**Comment by ruiwu1990** [comment] 2015-07-13 20:09
One question about code refactoring. There is a rule about coding that the maximum length of each line is 79. However, it is so hard for me to follow this rule. Here is an example:

```
        temp_variable_object = \
        NetCDFInformation(temp_variable_name, \
                      len(netcdf_aim_file.variables[temp_variable_name].dimensions), \
                      list(netcdf_aim_file.variables[temp_variable_name].dimensions))
```

I need to keep the indentation and it is so hard to keep each line less than 79. What should I do?

**Comment by mtpain** [comment] 2015-07-13 20:18
The following would be an improvement that would solve the 79 column rule as well as improve your code:

```python
temp_dims = list(netcdf_aim_file.variables[temp_variable_name].dimensions)
temp_dims_len = len(temp_dims)
temp_variable_object = NetCDFInformation(temp_variable_name, temp_dims_len, temp_dims)
```

Sometimes it's OK to exceed 79 columns, but in this case the refactor is simple to avoid going beyond 79. Also in Python you don't need the line extension `\` if you are inside parenthesis, brackets, or braces (`()`, `[]`, or `{}` respectively).

So often you can write

```python
v = long_named_function(arguement1, argument2, 
                                          argument3, argument4)   
```

As I've done here, the next line should align so that the first character of the first argument aligns with the first character of the first argument on the next line.

**Comment by mt-digital** [comment] 2015-07-13 20:20
The following would be an improvement that would solve the 79 column rule as well as improve your code:

``` python
temp_dims = list(netcdf_aim_file.variables[temp_variable_name].dimensions)
temp_dims_len = len(temp_dims)
temp_variable_object = NetCDFInformation(temp_variable_name, temp_dims_len, temp_dims)
```

Sometimes it's OK to exceed 79 columns, but in this case the refactor is simple to avoid going beyond 79. Also in Python you don't need the line extension `\` if you are inside parenthesis, brackets, or braces (`()`, `[]`, or `{}` respectively).

So often you can write

``` python
v = long_named_function(arguement1, argument2, 
                        argument3, argument4)   
```

**Comment by ruiwu1990** [comment] 2015-07-14 21:11
I am working on enabling users to upload their files. And then the system can visualize the uploaded files. The next step I will work on link the system to virtual watershed DB. After that, users can choose files to visualize from DB. If you guys have any suggestions about accessing data or interface design please feel free to email me.

I refactored most parts of my code and also set up index page for my section. The index page can help users to choose visualize csv files or NetCDF files.

**Comment by ruiwu1990** [comment] 2015-07-16 22:42
I just updated my part. Here is the clone url:
https://github.com/ruiwu1990/vwplatform.git

(If it does not work, it must because I did not push all my updates to my repository...) 

The latest version has following features: 
1) nicer interface
2) enable users upload files (stored in /vwplatform/app/visualization/tempData)  and visualize them.
3) enable users take a screenshot of the visualization results. The system will display it in a new tab of your browser.
4) I add some instructions in the webpage. I hope them helpful. :)

Oh, plz give me a hug guys (づ｡◕‿‿◕｡)づ.

**Comment by ruiwu1990** [comment] 2015-07-24 18:34
I have created an interface for Chase to visualize their csv output strings. I am now working on display netCDF file into a 2D map and I got a problem about color display (the bigger number with darker color, and the smaller number with lighter color). Can you guys give me some suggestions? How to deal with this?

I used the function (inputs are the number and the maximum of all the numbers) below to convert input value into a color (just have green and red components)

```
function convertValueIntoColor(inputValue, maxArrayValue)
{
    var greenNum = 255;
    var redNum = Math.floor(greenNum - (greenNum*inputValue/maxArrayValue));
    var tempHexString;
    greenNum = Math.floor(greenNum*inputValue/maxArrayValue);
    var greenString;
    var redString;
    //if red num < 16 then when you change it into string it will be just one letter not "0f"
    if(redNum == 0)
        redString = "00";
    else if(redNum < 16)
        redString = "0" + redNum.toString(16);
    else
        redString = redNum.toString(16);
    if(greenNum == 0)
        greenString = "00";
    else if(greenNum < 16)
        greenString = "0" + greenNum.toString(16);
    else
        greenString = greenNum.toString(16);
    return tempHexString = "#" + redString + greenString + "00";
}
```

The output is:
![my_2dmap](https://cloud.githubusercontent.com/assets/8552440/8881776/25f55fd4-31f7-11e5-94dc-eef246ca881a.png)

This is not as good as ncview outputs:
![ncview_2dmap](https://cloud.githubusercontent.com/assets/8552440/8881790/4db28268-31f7-11e5-8e71-465e47570e80.png)

When I change my function to display value with #FFFFFF scale by using the following function:

```
function convertValueIntoColor(inputValue, maxArrayValue)
{
    // 16777215 is #FFFFFF
    colorValue = 16777215 * inputValue / maxArrayValue;
    colorStr = '#' + ('00000' + (colorValue | 0).toString(16)).substr(-6); 
    return colorStr;
}
```

The output is ridiculous:
![2dmap](https://cloud.githubusercontent.com/assets/8552440/8881851/c2f65374-31f7-11e5-828a-b49cb40933df.png)

**Comment by ruiwu1990** [comment] 2015-07-27 23:46
I improved my map part based on suggestions from Chase and plot data with three colors. The results are below:

![threecolor](https://cloud.githubusercontent.com/assets/8552440/8920505/d3903810-347e-11e5-9bb4-e921aa2eac81.png)

My original program has the results:

![twocolor](https://cloud.githubusercontent.com/assets/8552440/8920509/de3fd0a4-347e-11e5-972f-f36897f506d7.png)

Can you guys tell me which you prefer or some other suggestions?

**Comment by mt-digital** [comment] 2015-07-28 19:59
OK, this is a great start.

For now, don't worry about refactoring and perfect code, let's get a good prototype of this going. 

This is a challenging problem. You're basically having to come up with your own colormap for use with scientific data on the web. The way you're doing it right now is slightly ineffective, but you're on the right track. I don't know how to do this well, and I think figuring out how to incorporate this into a map for the web is a major contribution.

I have a few ideas. The first is just to use grayscale, which means going from #000000 to #ffffff in single hexadigit steps, i.e.,
#000000, #010101, #020202, #030303, ..., #efefef, #ffffff.

In the longer term, let's try to get a nice colormap using some of the ideas below:

A good explanation of coloring maps: http://roadtolarissa.com/coloring-maps/

Not as good, but some supplementary info is here:
http://www.jeromecukier.net/blog/2011/08/11/d3-scales-and-color/

Again, the goal is to take the range of floating point values found in the figure as input and output one of 256 colors. I think if you follow the guidance in the first link you will get a better result. 

These links might also be helpful that discuss using a library called [chroma.js](https://github.com/gka/chroma.js):
- https://vis4.net/blog/posts/avoid-equidistant-hsv-colors/ (from the author of chroma.js)
- http://bl.ocks.org/mbostock/3014589 (example of using chroma.js in d3 by d3 creator Mike Bostock)

**Comment by ruiwu1990** [comment] 2015-07-28 20:09
Hi Matthew,

Thank you for the help. There are four things in my mind that I need to do:

1) Display the canvas (the 2D map stuff) on a google map
2) Correct my 2D map bugs. These are about how to make 2D maps working for
all kinds of polygon data, not just rectangular.
3) Improving 2D map color. As you suggested, I will use D3 scales.
4) Remove all global variables in my view.py

Because we should prepare a good prototype, I should focus on 1) and 2)
first right?

Best regards,
Rui

**Comment by mt-digital** [comment] 2015-07-28 20:54
I'd say the order would be 3), 1), 2), 4). 

But for fixing color, just get something like this and move on: 
![screen shot 2015-07-28 at 1 17 20 pm](https://cloud.githubusercontent.com/assets/2425472/8942618/2ce163ba-352b-11e5-8bc6-c2b268a28846.png)

Then getting 1) will give the user a better frame of reference.

2) is not too important for other kinds of polygon data at the moment, so leave this for later.

**Comment by ruiwu1990** [comment] 2015-07-28 22:12
3) is done for now. There is a screenshot about I_lw in of flat_input.nc
below. I used easting as lat and northing as lon. I found there was a new
bug for my map part. I will fix it this week.

Before next Thursday, I hope I can put the canvas on a google map. From
August 7th to August 14, I will not be in Nevada.

[image: Inline image 1]

**Comment by ruiwu1990** [comment] 2015-07-28 22:14
En. I am not sure why the image does not display. Here is the my screenshot.
![screenshot from 2015-07-28 15 04 33](https://cloud.githubusercontent.com/assets/8552440/8945336/5c0d3a1e-353b-11e5-860c-0ff13b17a31d.png)

**Comment by mt-digital** [comment] 2015-07-28 22:21
Excellent!

**Comment by ruiwu1990** [comment] 2015-07-30 18:51
I hesitate to overlay a canvas or an image on a google map. I can do both. If I choose to overlay a canvas, it is easier to react users' click on the overlay than using an image overlay. e.g. when users click on the overlay, I can display the details with a line chart about the chosen lat and lon. However, it will be slower than an image overlay. Users can feel the lagged. You can play my canvas overlay. Here is the url:

```
https://github.com/ruiwu1990/vwplatform.git
```

Here is an screenshot of my part:
![screenshot from 2015-07-30 11 36 05](https://cloud.githubusercontent.com/assets/8552440/8992001/fca9311e-36b0-11e5-9f38-fd751b6927a5.png)

P.S: I know I need to correct my overlay position. I am working on it now.

**Comment by mt-digital** [comment] 2015-07-30 22:52
That's looking great. I'm not sure what you should do for now, it depends on how slow it is. I'd say for now if you aren't using advanced features from the canvas, go with the image overlay. Either way, keep both in your code and comment out the one you don't use. We don't have to get rid of either at this point.

**Comment by ruiwu1990** [comment] 2015-07-31 23:04
I overlayed an image on google map and the left top point & right down point to locate the image position. Users can remove and add the overlay. I found the image was not match google map totally. I will figure out the reason next week. The outputs are displayed as below:
![1](https://cloud.githubusercontent.com/assets/8552440/9019262/a613a260-379d-11e5-8587-35f9214d917b.png)
![screenshot from 2015-07-31 15 55 13](https://cloud.githubusercontent.com/assets/8552440/9019263/a8fc82b2-379d-11e5-8c3a-1bc72444297f.png)

**Comment by ruiwu1990** [comment] 2015-08-04 23:16
I am now trying to change the overlay of the google map based on time. I met a magic thing. I know it is a bug. But it does not make any sense! Can you guys just give me a hint what is going on with this bug?

```
>>> json_projects_location[0]
{'lat': 43.732265, 'lon': -116.14284, 'data': [303.92157, 301.96078, 303.92157, 303.92157, 301.96078, 300.0, 301.96078, 301.96078, 298.03922, 303.92157, 315.68628, 321.56863, 329.41177, 331.37256, 331.37256, 333.33334]}
```

This is my json_projects_location[0]. I need to convert it into json. Therefore, I did this:

```
json.dumps(json_projects_location[0], separators=(',',':'))
```

There is a bug about this. OK, I accept that. However, if I did this:

```
json.dumps({'lat': 43.732265, 'lon': -116.14284, 'data': [303.92157, 301.96078, 303.92157, 303.92157, 301.96078, 300.0, 301.96078, 301.96078, 298.03922, 303.92157, 315.68628, 321.56863, 329.41177, 331.37256, 331.37256, 333.33334]}, separators=(',',':'))
```

This part works without bugs. This does not make any sense. I just copy paste json_projects_location[0] into json.dumps. If this works the previous part should not come up with a bug. Can someone give me some hints?

P.S.: Life is hard and programming is harder.

**Comment by ruiwu1990** [comment] 2015-08-05 21:45
Problem fixed! I finished converting the chosen data from NetCDF file into JSON file and passing them to the front end. I am working on display these data with overlay based on time.

**Comment by ruiwu1990** [comment] 2015-08-06 22:43
I added a button named "Next Time Overlay". Users can press this button to visualize next timestamp data with 2D map directly. I will change this button into a play button later. When users click this button the canvas will play the data change with time directly.

![screenshot from 2015-08-06 15 36 41](https://cloud.githubusercontent.com/assets/8552440/9125018/0dc2ba06-3c51-11e5-85ba-ff3f32acf9b8.png)

I have tested flat_input.nc file, which can be found in vwplatform/app/visualization/tempData. I chose to visualize 'I_lw' with option 'map_other', using 'lat' and 'lon' to be latitude and longitude. You can tried my latest part from my repo:

https://github.com/ruiwu1990/vwplatform.git

If it does not work, just copy and paste visualization folder in app/ and app/template into your working wc-wave part.

**Comment by ruiwu1990** [comment] 2015-08-19 18:13
I have added a slider, play, and pause buttons into my part. Users can press 'play' button to display data of different time (based on the 'time' variable) just like playing a video. Users can pause the slide show by pressing 'pause' button. Users can also start the slide show from different time stamps using the slider.

![screenshot from 2015-08-19 11 05 23](https://cloud.githubusercontent.com/assets/8552440/9364623/34d7d46c-4662-11e5-9c30-cbd658444f7b.png)

**Comment by ruiwu1990** [comment] 2015-08-27 17:12
For the new sample data (http://vwp-dev.unm.edu/apps/vwp/datasets/213b010b-1fd7-4b54-8c96-cfbcf6ff42c2/twoweek_inputs_with_zlib.nc.original.nc), my original program can present them in 2D map. I tested last night. My part took 37.5 minutes to load data. It takes so long time because it has 148 \* 170 \* 400 records in total. I think maybe I should not load all data before visualize them. I should stream data to visualize. Here is a screenshot of my part visualizing this sample file:

![screenshot from 2015-08-27 10 09 36](https://cloud.githubusercontent.com/assets/8552440/9527422/efb2ea32-4ca3-11e5-821b-98a57e70ceed.png)

**Comment by ruiwu1990** [comment] 2015-08-31 22:46
After some researches and help from my lab teachers, I got two ideas for this slow map visualization problem (loading time is too long, 148 \* 170 \* 400 takes half hour). Please tell me, which one you prefer or you prefer both (I will offer options for users).

First idea, users choose to create a video based on the variable they have chosen. After the video is created, the server will send users a download link of the video. e.g. User A chooses to visualize 'I_lw' of a sample file. User A chooses variable 'lon' to be longitude, variable 'lat' to be latitude, and dimension 'time' to be the label of each frame. The system displays a page with message: "order received". After the system puts all the data into frames and frames into a mp4 file. The system will send User A a download link of the created mp4 file.

Second idea, users can display 5 frames at most each time. After the first 5 frames are played, the user should press a button 'next 5 frame'. Then, the system will send a request to server to grab the next 5 frames data.

**Comment by ruiwu1990** [comment] 2015-09-09 18:52
Help Wanted

After some experiments I found extraction data from netCDF file takes most of the time. But I really don't know why it take so much time. I used something that is similar to the following code to extract 'I_lw' from flat_input.nc (http://vwp-dev.unm.edu/apps/vwp/datasets/4a79a65f-05f5-4bc1-8a75-59dbe0b0edaf/flat_input.nc.original.nc):

``` python
import time
from netCDF4 import Dataset

def extract_data():
    filename='flat_input.nc'
    variable_name='I_lw'
    netcdf_aim_file = Dataset(filename, "r")
    # length of northing is 148
    lat_lon_first_dimension_length = 148
    # length of easting  is 170
    lat_lon_second_dimension_length = 170
    # extract time from 0 to 15
    # end frame is 16 not 15 coz range(0,16) ends 15
    start_frame = 0
    end_frame = 16
    # record start time
    start_time = time.time()
    for count_lat_lon_first in range(0,lat_lon_first_dimension_length):
        for count_lat_lon_second in range(0,lat_lon_second_dimension_length):
            temp_array = []
            for count_other in range(start_frame,end_frame):
                temp_array.append(netcdf_aim_file.variables[variable_name][count_other][count_lat_lon_first][count_lat_lon_second].item())
            # the following part is about put temp_array into json file
            # which is not listed here
    print("--- extraction data uses %s seconds ---" % (time.time() - start_time))
```

The results is : 

```
--- extraction data uses 58.7738940716 seconds ---
```

This means the program used around 58 seconds to extract 148 \* 170 \* 16 records. Can someone just give me some hints why it takes so long? Thank you so much.

**Comment by itsrifat** [comment] 2015-09-09 20:31
@ruiwu1990  DId you try using standard numy way ?

If I run the following code:

``` python
import time
from netCDF4 import Dataset
filename='flat_input.nc'
netcdf_aim_file = Dataset(filename, "r")
variable_name='I_lw'
start_frame = 0
end_frame = 16

start_time = time.time()
temp_array = netcdf_aim_file.variables[variable_name][:][:][start_frame:end_frame]
print("--- extraction data uses %s seconds ---" % (time.time() - start_time))
print("shape of temp_array" + temp_array.shape)

```

This is the output I get:

``` text
--- extraction data uses 0.135038852692 seconds ---
('shape of temp_array:', (16, 148, 170))
```

So it takes only .1 seconds. Don't use loops to extract values of a numpy array.They are already vectorized. That's the reason for using numpy :)

**Comment by ruiwu1990** [comment] 2015-09-09 20:44
OHOHOHOHOH!!!!!!

Yep, that's super fast!! I should use numpy instead of list. Thank you so much. I tested by myself. It works!!!

**Comment by ruiwu1990** [comment] 2015-09-10 20:50
Wow! I feel so happy to say my 2D part is super fast now after I rewrote them based on Moinul's suggestions. Muhahaha, thank you Moinul!

![screenshot from 2015-09-10 13 42 34](https://cloud.githubusercontent.com/assets/8552440/9800607/baf52a9c-57c2-11e5-9bda-c7d66c9205d3.png)

**Comment by itsrifat** [comment] 2015-09-10 22:24
:+1:

**Closed as completed** 2015-10-02 17:05 UTC
Labels: enhancement, help wanted
